### ISSUE TITLE
Inconsistent version numbers

### ISSUE THREAD

**Issue by Rhialto** [Fish-Git/decNumber-icu-368#4]
The README.md file claims this is 
```
#### version 3.68.0
```
but the build script says
```
  _versnum="2.5"
```
Which is correct?

**Comment by wrljet** [comment]
I believe `_versnum="2.5"` refers to the script itself.  Not the package overall.

**Comment by Rhialto** [comment]
I'm trying to clean up the packaging in pkgsrc for these libraries, so I was looking for the correct version number to use. And the same with the other libraries, of course.

**Comment by Fish-Git** [comment]
Bill is correct: 2.5 is the version number of the _build script_, not the package.

The version number of the _package_ is defined by statements within the package's [CMake script](https://github.com/SDL-Hercules-390/decNumber/blob/master/CMakeLists.txt):

https://github.com/SDL-Hercules-390/decNumber/blob/da6650957d7dea21b5647c1fa80fa432f2891550/CMakeLists.txt#L9-L18

which matches both the packages's documentation (README) and what is reported by Hercules too during startup as well:

<pre>
HHC01417I Built with crypto external package version 1.0.0.49-g837705e
<b>HHC01417I Built with decNumber external package version 3.68.0.99-gda66509</b>
HHC01417I Built with SoftFloat external package version 3.5.0.102-g42f2f99
HHC01417I Built with telnet external package version 1.0.0.59-g2aca101
</pre>

Closing as Invalid (User Error).
